---
title: "Tarea 5"
output:
  html_document:
    df_print: paged
---
#empezamos con la tarea 5
library(tidyquant)
#Descargando precios de los activos (Microsoft y Apple)
tickers <- c("MSFT","AAPL")
Data_Activos  <- tq_get(tickers, 
                        get = "stock.prices", 
                        from = "2000-01-01", 
                        to = "2018-08-30", 
                        periodicity = "monthly")

# retornos 
retornos_activos <- Data_Activos %>% 
  group_by(symbol) %>% 
  tq_transmute(select = close,
               mutate_fun = periodReturn,
               period = "monthly",
               type = "log",
               col_rename = "retornos.mensuales")
#Retornos acumulados
retornos_acum_activos <- retornos_activos %>% 
  group_by(symbol) %>% 
  mutate(ret.cum = cumsum(retornos.mensuales))

#Grafico retornos de ambas acciones 
retornos_activos %>% 
  ggplot(mapping = aes(x = retornos.mensuales, fill = symbol))+
  geom_density(alpha = 0.5) +
  labs(title = "Retornos Activos", subtitle = "Microsoft (MSFT), APPLE (AAPL)",
       x = "Retornos mensuales", y = "Densidad") + 
  theme_tq() +
  scale_fill_tq() + 
  facet_wrap(~ symbol, ncol = 2) + 
  guides(fill=guide_legend(title="Activos:"))

# Grafico retornos acumulados de ambas acciones

retornos_acum_activos %>% 
  ggplot(mapping = aes(x = date, y = ret.cum/100, color = symbol)) +
  geom_line() + 
  labs(title = "Retornos Activos", subtitle = "Microsoft (MSFT), APPLE (AAPL)",
       x = "Periodo", y = "Retorno Acumulado") + 
  theme_tq() +
  scale_fill_tq() + 
  facet_wrap(~ symbol, ncol = 2) + 
  guides(color = guide_legend(title="Activos:")) + 
  scale_y_continuous(labels = scales::percent)


#testnormalidad
 




